### ISSUE TITLE
A problem importing module readline

### ISSUE THREAD

**Issue by null12138** [peter-hunt/skyblock#2] opened 2021-07-12 01:47 UTC
emm
hi bro~
i dont know why i cant using readline
that is warning said
![skyblock](https://user-images.githubusercontent.com/53962221/125218794-3725fa00-e2f6-11eb-9f34-f6ab890f673f.PNG)

**Comment by null12138** [comment] 2021-07-12 01:49
can  u help me to slove it error?
i am really want to play ur skyblock in cmd

**Comment by null12138** [comment] 2021-07-12 01:49
btw , i cant install readlne

**Comment by peter-hunt** [comment] 2021-07-18 02:32
Fixed by replacing the history function with an empty one, in case the module readline cannot be installed or imported. The problem should be fixed so the issue is closed.

**Closed as completed by peter-hunt** 2021-07-18 02:32 UTC
